### PR TITLE
Updates to support GNOME Shell 43

### LINKED ISSUE #9: Please add support for Gnome 43
Hi admin,

Please add support for Gnome 43, thanks

### LINKED ISSUE #10: Fix conflict with "Autohide Battery" (extension id 595)
Was reported in a user review by [zcwwelkin](https://extensions.gnome.org/accounts/profile/zcwwelkin) on 2022 Oct 11.

> Tested in GNOME 42.5 this extension will conflicts with "Autohide Battery"(id 595), which also hides the username when autohide the battery icon.

### PR DESCRIPTION
**Pull request by Josholith**
I had to to refactor considerably since Aggregate menu has been replaced with Quick Settings menu in this GNOME version.  It's working locally for me on Arch Linux with GNOME Shell 43.  Closes #9.

As a side benefit, the username indicator is no longer tied to the power indicator with this refactor, so this PR closes #10.

Please let me know if any questions and feel free to adjust/change anything.

### CODE REVIEW

**Comment by brendaw** [comment]
Thanks @Josholith for your effort! I'll check this and merge as soon as possible!

**Comment by brendaw** [comment]
Reviewed and everything worked like a charm! 

Squashed and merged!

Thanks again!

**Comment by Josholith** [comment]
Excellent!  Just a courtesy reminder, you'll have to upload the ZIP to [extensions.gnome.org ](https://extensions.gnome.org)

As the code has changed a bit on this refactor, I expect it to not get automatically approved by the site but will require the site admins to provide a review.

When the extension is approved, it should get Activated just for Gnome Shell 43.  The previous version of this extension (version 8) can be kept active for all of Gnome 3.x - 42.  This way users of all Gnome versions will have access to the extension.  Folks on earlier Gnome versions will simply receive the older version of the extension, which still works fine on those versions.  When they update to Gnome 43 in the future, they will get an extension update to version 9.

**Comment by brendaw** [comment]
I've submitted just now the extension to the site :)

Hope that they review it as quickly as possible.

And I notice that, the change you have made on the compatibility. This was amazing on your part, really appreciated it hehe

**Pull request merged**
